# Generated by Django 5.2.11 on 2026-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="state",
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile",
            field=models.CharField(default="Not provided", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default="password", max_length=128),
        ),
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.CharField(default="customer", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
