# Generated by Django 5.2.11 on 2026-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
