# Generated by Django 5.2.11 on 2026-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_username", models.CharField(db_index=True, max_length=100)),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("total_bill", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_date", models.DateTimeField()),
                ("items", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
